### ISSUE TITLE
First call to watch on vpc results in duplicate VPC objects

### ISSUE THREAD

**Issue by reachjainrahul** [antrea-io/nephe#137]
**Describe the bug**

First time when 'kubectl get vpc -A -w' is executed, it dumps VPC info twice. 

**To Reproduce**

Add CPA object and set up watch. VPC will be dumped twice in the output
root@rjdev2:~/new/nephe# kubectl get vpc -A -w | grep vpc-0d977c10c34e6722a 
demo-ns-one   vpc-0d977c10c34e6722a   AWS              us-west-2   false
demo-ns-one   vpc-0d977c10c34e6722a   AWS              us-west-2   false

**Expected**

There should be only one instance of VPC

**Actual behavior**

**Versions:**

**Additional context**

**Comment by bangqipropel** [comment]
It is on upstream codebase, have filed a issue here:
[](https://github.com/antrea-io/antrea/issues/4672)

**Comment by reachjainrahul** [comment]
Wont fix. This happens only for queries made via kubectl get. If a watch is setup using explicit client, no issue is seen there.
