### ISSUE TITLE
Add VpcId label to ExternalEntity CRs

### ISSUE THREAD

**Issue by chidambaramgvmware** [antrea-io/nephe#160]
**Describe the problem/challenge you have**
Currently, there is no label added to EE identifying the Cloud VPC they are part of. This will be needed to support VPC scoped Groups/ANP

**Describe the solution you'd like**
Add a VpcId label to EE referring to the Cloud VPC ID so that we can use this for labelSelector  during Group/ANPcreation.

**Anything else you would like to add?**

**Comment by reachjainrahul** [comment]
It is already support. Please check vpc.nephe label @chidambaramgvmware

**Comment by chidambaramgvmware** [comment]
@reachjainrahul I believe vpc.nephe label has the Nephe generated VPC name and not the cloud provided ID or name. From consumption perspective, we would need the following labels in the EE CR,

vpc.cloud.name - Name of VPC on public cloud
vpc.cloud.id - VPC/VNET ID generated by public cloud provider
vm.cloud.name - Name of VM on public cloud
vm.cloud.id - VM ID generated by public cloud provider

These will be the labels we will be configuring in the labelSelector of Group CR to select cloud VMs as part of a Group.
I believe in the case of Azure, cloud generated ID is of the URL format with "/" which k8s labels don't support, so adding the resourceGuid which is of the UUID format would be good.
