### ISSUE TITLE
Do not normalize Cloud Tags

### ISSUE THREAD

**Issue by chidambaramgvmware** [antrea-io/nephe#171]
Nephe discovers the cloud tags for a VM and adds it to the "Tag" field in the VM runtime object & "label" field of the EE CR. But, incase of tags with special characters like "/" in them, the "Tag" field in the VM object has the value as-is but the "label" has it in a different format which is normalized to fit the character criteria of k8s labels. 

From a Policy consumption perspective, it is confusing since the Tag field in the VM object doesn't match the corresponding labels added to EE CR for discovered tags.

Can we just ignore such tags which are of unsupported k8s format & update the Nephe documentation to reflect the same?

**Comment by archanapholla** [comment]
Implemented as part of https://github.com/antrea-io/nephe/pull/201 PR
