### ISSUE TITLE
vmp goes into in-progress state briefly after nephe controller restart with anp applied

### ISSUE THREAD

**Issue by shenmo3** [antrea-io/nephe#177]
**Describe the bug**
When the Nephe controller is restarted with an ANP applied, the vmp goes into the in-progress state briefly, even when there are no changes in the cloud.

**To Reproduce**
1. Import some VMs and apply an ANP.
2. Restart the Nephe controller.
3. Check the controller log.

**Expected**
The vmp should remain in the applied state, as there are no changes to the cloud.

**Actual behavior**
The controller log shows that the vmp briefly goes into the in-progress state, then returns to the applied state.

**Versions:**
v0.4.0

**Additional context**
N/A

**Comment by reachjainrahul** [comment]
Fixed
