### ISSUE TITLE
Terraform script is not deleting vpc if security group exists

### ISSUE THREAD

**Issue by reachjainrahul** [antrea-io/nephe#38]
**Describe the bug**

When aws-tf script is used to delete the vpc, it fails to delete it completely if there are any security groups present in that vpc

**To Reproduce**

create a vpc using aws-tf create and then from aws console create additional security group in that vpc and then come back to aws-tf and try to destroy the vpc using aws-tf destroy command. It will fail with dependency error

**Expected**

**Actual behavior**

**Versions:**

Nephe v0.1.0

**Additional context**

**Comment by bangqipropel** [comment]
I tried this and found that not only SGs but other dependencies also will cause this problem. I tried to find a way that can fix all kinds of dependencies, but seems like not easy. 
https://aws.amazon.com/premiumsupport/knowledge-center/troubleshoot-dependency-error-delete-vpc/

So I think we have two options here:
1. We just check if we have SGs on VPC, using the terraform "import" to find it and then delete it.
2. We can use the AWS CLI to check common dependencies like: https://serverfault.com/questions/648332/how-to-list-all-vpc-dependencies-in-aws-cli , then delete all of them
